import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import { rebuild } from "../src/Rebuilder.js";
import { DataEntry } from "../src/types/DataEntry.js";

describe("rebuilder", () => {
  const samples: Array<[string, DataEntry[][]]> = [
    ["example", [[]]],
    ["example2", [[], [["Hello", "Hello", 0]]]],
    ["example3", []],
    [
      "example4",
      [
        [
          ["A", "123", 0],
          ["B", "456", 1],
        ],
      ],
    ],
    [
      "example5",
      [
        [
          ["A", "123", 1],
          ["B", "456", 0],
        ],
      ],
    ],
    [
      "example9",
      [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [["xxxxxxxxxx", "Hello", 0]],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
      ],
    ],
  ];

  it.each(samples)("rebuild(%s.msbt)", (file, entries) => {
    expect(rebuild(entries)).toStrictEqual(
      readFileSync(`${__dirname}/fixtures/${file}.msbt`),
    );
  });
});
